spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.indent_output = true

# This configures Spring Boot to trust and use forwarded headers (like X-Forwarded-For) when behind a proxy or load balancer
server.forward-headers-strategy=framework 

server.port=8080
ADYEN_API_KEY=AQFDhmfxKI/HaxVCw0m/n3Q5qf3VaY9UCJ16aExb1nSuk2NFisZiGclvMiVgB/7xzYuhmDgJcejDpmGOcxskemR7Zp/8GxDBXVsNvuR83LVYjEgiTGAH-FVAwZAK1Oy9k6D1w9bAVXgedJ8NFJUZuHs2ali/f+ec=-i1ih{@2$%7H:fJGY^Rp
ADYEN_MERCHANT_ACCOUNT=AdyenPPImplementationTrainingTest_null_TEST
ADYEN_CLIENT_KEY=test_6RRXQYWJX5E65LUYQHDMHOITZIA56UH4
ADYEN_HMAC_KEY=A5EB2AF54F5A6D1B061D4403A4253FDBB3DE7ED3DA00BE3165F6FA5A04E0EDD9
